# Generated by Django 5.0.4 on 2024-04-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_back', '0002_users_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
